### PR TITLE
New Device Support

### PR DESCRIPTION
**Pull request by Be2daErtin**
Added support for Dimmer and RGBW.
Also added additional zWave features (Disconnect, Value Update and Notifications)

### CODE REVIEW

**Comment by mike182uk** [comment]
Hey @Be2daErtin 

Thanks for this!

Unfortunately it looks like there is a merge conflict - I've taken a look to see if I can resolve it but it looks like the branches have diverged quite a bit since the `2.1.0` release.

Would you mind opening up a new pull request with your changes made against the latest master as I don't think it's going to be an easy task resolving this merge conflict.

Hopefully you should just be able to move the methods you have added across without much hassle.

Let me know how you get on 👍

**Comment by Be2daErtin** [comment]
Hi,

Will do as soon as I can.

You've changed the way on how devices characteristics are set. Need to get my head around the way you've done it. Will then update.

**Comment by Be2daErtin** [comment]
Hmmmm... I think your new code does not allow for multiple characteristics on one device. For example, a dimmable device has "On" and "Brightness" characteristics.

**Comment by mike182uk** [comment]
Hey @Be2daErtin 

> You've changed the way on how devices characteristics are set. Need to get my head around the way you've done it. Will then update.

Yeah, I refactored things to make them a bit more DRY. If you check out the a simple service like the [Humidity Sensor](https://github.com/mike182uk/homebridge-zwave/blob/master/lib/AccessoryManager.js#L194) it should hopefully be a little clearer.

> Hmmmm... I think your new code does not allow for multiple characteristics on one device. For example, a dimmable device has "On" and "Brightness" characteristics.

I haven't changed anything around what characteristics a device can have, you can see [here](https://github.com/mike182uk/homebridge-zwave/blob/master/lib/AccessoryManager.js#L136) for an example of a service that declares 2 characteristics on the device

**Pull request closed without merging**
